In [3]:
import numpy as np

In [5]:
pares = np.array( [2, 4, 6, 8] )
pares

array([2, 4, 6, 8])

In [17]:
print(pares.ndim)
print(pares.shape)
print(pares.dtype)

1
(4,)
int64


In [11]:
escalar = np.array( 10 )
escalar

array(10)

In [13]:
escalar.ndim

0

In [19]:
pares.astype(np.float32)

array([2., 4., 6., 8.], dtype=float32)

In [21]:
pares.dtype

dtype('int64')

In [23]:
pares.astype(np.int8)

array([2, 4, 6, 8], dtype=int8)

In [25]:
pares.astype(np.uint64)

array([2, 4, 6, 8], dtype=uint64)

In [29]:
pares.dtype

dtype('int64')

In [31]:
pares_positivos = pares.astype(np.uint64)
pares_positivos.dtype

dtype('uint64')

In [45]:
matriz_2d = np.array( [ [2, 3, 4], [7, 8, 9] ], dtype=np.uint8 )

In [47]:
print(matriz_2d.ndim)
print(matriz_2d.shape)
print(matriz_2d.dtype)

2
(2, 3)
uint8


In [49]:
tudo_um = np.ones( [7, 3] )
tudo_um

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
tudo_zero = np.zeros( [4, 2] )
tudo_zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
faixa1 = np.arange( -10.0, 10.0, 0.1, dtype=np.float16 )
faixa1

array([-10.     ,  -9.9    ,  -9.8    ,  -9.695  ,  -9.59   ,  -9.49   ,
        -9.39   ,  -9.29   ,  -9.19   ,  -9.086  ,  -8.984  ,  -8.88   ,
        -8.78   ,  -8.68   ,  -8.58   ,  -8.48   ,  -8.375  ,  -8.27   ,
        -8.17   ,  -8.07   ,  -7.97   ,  -7.867  ,  -7.766  ,  -7.664  ,
        -7.562  ,  -7.46   ,  -7.36   ,  -7.258  ,  -7.156  ,  -7.055  ,
        -6.953  ,  -6.85   ,  -6.75   ,  -6.65   ,  -6.547  ,  -6.445  ,
        -6.344  ,  -6.242  ,  -6.14   ,  -6.04   ,  -5.938  ,  -5.836  ,
        -5.734  ,  -5.633  ,  -5.53   ,  -5.43   ,  -5.33   ,  -5.227  ,
        -5.125  ,  -5.023  ,  -4.92   ,  -4.82   ,  -4.72   ,  -4.617  ,
        -4.516  ,  -4.414  ,  -4.312  ,  -4.21   ,  -4.11   ,  -4.008  ,
        -3.906  ,  -3.805  ,  -3.703  ,  -3.602  ,  -3.5    ,  -3.398  ,
        -3.297  ,  -3.195  ,  -3.094  ,  -2.992  ,  -2.89   ,  -2.79   ,
        -2.688  ,  -2.586  ,  -2.484  ,  -2.383  ,  -2.281  ,  -2.18   ,
        -2.078  ,  -1.977  ,  -1.875  ,  -1.773  , 

In [93]:
pares = np.array( [2, 4, 6, 8, 10, 12, 14, 16, 18], dtype=np.uint8 )
primos = np.array( [1, 2, 3, 5, 7, 11, 13, 17, 19], dtype=np.uint8 )
print(pares)
print(primos)

[ 2  4  6  8 10 12 14 16 18]
[ 1  2  3  5  7 11 13 17 19]


In [99]:
#tudo_junto = np.concatenate( [pares, primos] )
tudo_junto = np.array( [pares, primos] )
print(tudo_junto)
print(tudo_junto.ndim)
print(tudo_junto.shape)
print(tudo_junto.dtype)

[[ 2  4  6  8 10 12 14 16 18]
 [ 1  2  3  5  7 11 13 17 19]]
2
(2, 9)
uint8


In [101]:
matriz2d_zeros = np.zeros_like( tudo_junto )
matriz2d_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [105]:
np.zeros( tudo_junto.shape, dtype=tudo_junto.dtype ) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [111]:
numeros_aleatorios = np.random.random( [4, 7] ).astype(np.float16)
numeros_aleatorios

array([[0.9165  , 0.7305  , 0.01912 , 0.554   , 0.879   , 0.2986  ,
        0.2373  ],
       [0.9937  , 0.3533  , 0.767   , 0.09015 , 0.1179  , 0.9243  ,
        0.075   ],
       [0.61    , 0.3635  , 0.259   , 0.9746  , 0.6616  , 0.1342  ,
        0.06113 ],
       [0.007206, 0.2915  , 0.1746  , 0.7603  , 0.6973  , 0.2017  ,
        0.621   ]], dtype=float16)

In [125]:
numeros_inteiros_aleatorios = np.random.randint( 1, 61, [100, 6] )
numeros_inteiros_aleatorios

array([[ 9, 60, 28,  1,  4, 11],
       [24,  7, 11, 53, 11,  6],
       [39,  3, 54, 45, 14,  9],
       [31, 41, 48, 53, 17,  6],
       [52, 14, 19, 21, 14,  7],
       [ 8, 60, 38, 56, 37,  8],
       [ 2,  5, 16, 11, 44, 30],
       [ 1,  4, 53, 56, 30,  1],
       [34, 57, 60, 52, 55, 35],
       [51, 52, 49, 52, 49,  3],
       [37, 14, 57, 16,  9, 38],
       [49, 15, 28, 45, 55, 13],
       [53, 41, 56, 17, 25, 22],
       [18, 40, 56, 32, 13, 24],
       [59, 18,  9, 58, 18, 11],
       [13, 18, 48, 10, 12, 22],
       [13, 12, 52, 42, 58, 53],
       [32, 20, 29,  1, 30, 15],
       [37, 55, 27, 11, 19, 45],
       [10, 35, 19, 50, 44,  8],
       [33,  6, 59, 48, 17,  7],
       [47, 53, 39, 34, 31, 59],
       [40, 28,  1, 59, 14, 54],
       [53, 32, 44, 49, 20, 47],
       [27, 48, 11,  7, 17,  2],
       [28, 48, 48, 26, 51, 40],
       [17, 58, 43, 42, 54, 50],
       [52, 28,  3, 56, 25, 24],
       [ 9, 11, 19, 59, 43, 27],
       [47, 39, 36, 36, 55, 26],
       [56

In [129]:
np.eye( 10 ) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])