In [1]:
import numpy as np

In [2]:
pares = np.array( [2, 4, 6, 8] )
pares

array([2, 4, 6, 8])

In [3]:
print(pares.ndim)
print(pares.shape)
print(pares.dtype)

1
(4,)
int64


In [4]:
escalar = np.array( 10 )
escalar

array(10)

In [5]:
escalar.ndim

0

In [6]:
pares.astype(np.float32)

array([2., 4., 6., 8.], dtype=float32)

In [7]:
pares.dtype

dtype('int64')

In [8]:
pares.astype(np.int8)

array([2, 4, 6, 8], dtype=int8)

In [9]:
pares.astype(np.uint64)

array([2, 4, 6, 8], dtype=uint64)

In [10]:
pares.dtype

dtype('int64')

In [11]:
pares_positivos = pares.astype(np.uint64)
pares_positivos.dtype

dtype('uint64')

In [12]:
matriz_2d = np.array( [ [2, 3, 4], [7, 8, 9] ], dtype=np.uint8 )

In [13]:
print(matriz_2d.ndim)
print(matriz_2d.shape)
print(matriz_2d.dtype)

2
(2, 3)
uint8


In [14]:
tudo_um = np.ones( [7, 3] )
tudo_um

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
tudo_zero = np.zeros( [4, 2] )
tudo_zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
faixa1 = np.arange( -10.0, 10.0, 0.1, dtype=np.float16 )
faixa1

array([-10.     ,  -9.9    ,  -9.8    ,  -9.695  ,  -9.59   ,  -9.49   ,
        -9.39   ,  -9.29   ,  -9.19   ,  -9.086  ,  -8.984  ,  -8.88   ,
        -8.78   ,  -8.68   ,  -8.58   ,  -8.48   ,  -8.375  ,  -8.27   ,
        -8.17   ,  -8.07   ,  -7.97   ,  -7.867  ,  -7.766  ,  -7.664  ,
        -7.562  ,  -7.46   ,  -7.36   ,  -7.258  ,  -7.156  ,  -7.055  ,
        -6.953  ,  -6.85   ,  -6.75   ,  -6.65   ,  -6.547  ,  -6.445  ,
        -6.344  ,  -6.242  ,  -6.14   ,  -6.04   ,  -5.938  ,  -5.836  ,
        -5.734  ,  -5.633  ,  -5.53   ,  -5.43   ,  -5.33   ,  -5.227  ,
        -5.125  ,  -5.023  ,  -4.92   ,  -4.82   ,  -4.72   ,  -4.617  ,
        -4.516  ,  -4.414  ,  -4.312  ,  -4.21   ,  -4.11   ,  -4.008  ,
        -3.906  ,  -3.805  ,  -3.703  ,  -3.602  ,  -3.5    ,  -3.398  ,
        -3.297  ,  -3.195  ,  -3.094  ,  -2.992  ,  -2.89   ,  -2.79   ,
        -2.688  ,  -2.586  ,  -2.484  ,  -2.383  ,  -2.281  ,  -2.18   ,
        -2.078  ,  -1.977  ,  -1.875  ,  -1.773  , 

In [17]:
pares = np.array( [2, 4, 6, 8, 10, 12, 14, 16, 18], dtype=np.uint8 )
primos = np.array( [1, 2, 3, 5, 7, 11, 13, 17, 19], dtype=np.uint8 )
print(pares)
print(primos)

[ 2  4  6  8 10 12 14 16 18]
[ 1  2  3  5  7 11 13 17 19]


In [18]:
#tudo_junto = np.concatenate( [pares, primos] )
tudo_junto = np.array( [pares, primos] )
print(tudo_junto)
print(tudo_junto.ndim)
print(tudo_junto.shape)
print(tudo_junto.dtype)

[[ 2  4  6  8 10 12 14 16 18]
 [ 1  2  3  5  7 11 13 17 19]]
2
(2, 9)
uint8


In [19]:
matriz2d_zeros = np.zeros_like( tudo_junto )
matriz2d_zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [20]:
np.zeros( tudo_junto.shape, dtype=tudo_junto.dtype ) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [21]:
numeros_aleatorios = np.random.random( [4, 7] ).astype(np.float16)
numeros_aleatorios

array([[0.963 , 0.6484, 0.9478, 0.5845, 0.627 , 0.3818, 0.8706],
       [0.2537, 0.352 , 0.6484, 0.3198, 0.856 , 0.2812, 0.4775],
       [0.902 , 0.4497, 0.6655, 0.1049, 0.2886, 0.1981, 0.3093],
       [0.8354, 0.613 , 0.941 , 0.4502, 0.9937, 0.928 , 0.4485]],
      dtype=float16)

In [22]:
numeros_inteiros_aleatorios = np.random.randint( 1, 61, [100, 6] )
numeros_inteiros_aleatorios

array([[26, 26, 53, 29,  4, 11],
       [ 1,  4, 49, 56, 43, 59],
       [58, 33, 48, 10, 57, 60],
       [ 4, 59, 31, 47, 19, 37],
       [47, 22,  8, 53, 60, 36],
       [32, 22, 19, 33, 30, 27],
       [23,  5, 40, 12, 10, 55],
       [33, 33, 57, 37, 13, 42],
       [51, 32, 21, 47,  6, 38],
       [32,  2, 20, 17, 36, 25],
       [31,  8,  9, 38, 19, 11],
       [11, 54, 12,  8, 50, 33],
       [ 5, 27, 51,  2, 36, 35],
       [40, 32, 33, 12,  3, 46],
       [34, 13, 31, 36, 23, 20],
       [34, 18, 49, 30, 33, 47],
       [29, 46, 27, 28, 53, 28],
       [59, 14, 30, 27, 58, 40],
       [60, 24, 23, 40, 41, 47],
       [ 3, 47, 33, 59, 13, 52],
       [ 3, 57, 25, 20, 41,  9],
       [59, 25, 29, 40, 12, 59],
       [52, 12, 40, 19, 15,  2],
       [42, 22, 24, 51,  6, 20],
       [10, 35, 52, 36,  2, 25],
       [19, 23, 20, 13, 58,  3],
       [42, 51, 12, 21, 10, 49],
       [55, 40, 36, 48, 43,  9],
       [41, 23, 27,  3, 44, 46],
       [56, 39, 28, 59,  8, 30],
       [16

In [23]:
np.eye( 10 ) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
numeros = np.random.randint( 1, 61, [10, 6] )
numeros

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [25]:
numeros.reshape( [6, 10] )

array([[35,  9,  3,  7,  4, 22, 21, 56, 48, 49],
       [46, 16, 52, 15, 50, 23, 17, 11, 36, 52],
       [23,  2, 14, 41, 39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51, 31, 34, 16, 37],
       [ 3, 43, 54, 19, 58, 53,  4, 48, 34,  9],
       [ 7, 17, 21, 13, 45, 39, 33, 46,  4, 25]], dtype=int32)

In [26]:
# np.transpose(numeros)
numeros.T

array([[35, 21, 52, 36, 39, 34, 31, 54, 34, 45],
       [ 9, 56, 15, 52, 40, 10, 34, 19,  9, 39],
       [ 3, 48, 50, 23, 57, 26, 16, 58,  7, 33],
       [ 7, 49, 23,  2, 49, 13, 37, 53, 17, 46],
       [ 4, 46, 17, 14,  4,  9,  3,  4, 21,  4],
       [22, 16, 11, 41, 38, 51, 43, 48, 13, 25]], dtype=int32)

In [27]:
numeros_flatten = numeros.flatten()

In [28]:
numeros_ravel = numeros.ravel()

In [29]:
numeros[0] = 1000

In [30]:
numeros

array([[1000, 1000, 1000, 1000, 1000, 1000],
       [  21,   56,   48,   49,   46,   16],
       [  52,   15,   50,   23,   17,   11],
       [  36,   52,   23,    2,   14,   41],
       [  39,   40,   57,   49,    4,   38],
       [  34,   10,   26,   13,    9,   51],
       [  31,   34,   16,   37,    3,   43],
       [  54,   19,   58,   53,    4,   48],
       [  34,    9,    7,   17,   21,   13],
       [  45,   39,   33,   46,    4,   25]], dtype=int32)

In [31]:
numeros = numeros_flatten.reshape( [10, 6] )

In [32]:
numeros_ravel

array([1000, 1000, 1000, 1000, 1000, 1000,   21,   56,   48,   49,   46,
         16,   52,   15,   50,   23,   17,   11,   36,   52,   23,    2,
         14,   41,   39,   40,   57,   49,    4,   38,   34,   10,   26,
         13,    9,   51,   31,   34,   16,   37,    3,   43,   54,   19,
         58,   53,    4,   48,   34,    9,    7,   17,   21,   13,   45,
         39,   33,   46,    4,   25], dtype=int32)

In [33]:
numeros

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [34]:
numeros.reshape( [4, -1] )

array([[35,  9,  3,  7,  4, 22, 21, 56, 48, 49, 46, 16, 52, 15, 50],
       [23, 17, 11, 36, 52, 23,  2, 14, 41, 39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51, 31, 34, 16, 37,  3, 43, 54, 19, 58],
       [53,  4, 48, 34,  9,  7, 17, 21, 13, 45, 39, 33, 46,  4, 25]],
      dtype=int32)

In [35]:
numeros1 = numeros 
numeros2 = numeros.copy()

In [36]:
numeros1

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [37]:
numeros

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [38]:
numeros[0, 0] = 1000

In [39]:
numeros1

array([[1000,    9,    3,    7,    4,   22],
       [  21,   56,   48,   49,   46,   16],
       [  52,   15,   50,   23,   17,   11],
       [  36,   52,   23,    2,   14,   41],
       [  39,   40,   57,   49,    4,   38],
       [  34,   10,   26,   13,    9,   51],
       [  31,   34,   16,   37,    3,   43],
       [  54,   19,   58,   53,    4,   48],
       [  34,    9,    7,   17,   21,   13],
       [  45,   39,   33,   46,    4,   25]], dtype=int32)

In [40]:
numeros2

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [41]:
np.savez("bolao.npz", jogos=numeros2)

In [42]:
data = np.load("bolao.npz")

In [92]:
numeros = data["jogos"]

In [98]:
uns = np.ones_like( numeros )
print(uns)
zeros = np.zeros_like( numeros )
print(zeros)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [104]:
numeros 

array([[35,  9,  3,  7,  4, 22],
       [21, 56, 48, 49, 46, 16],
       [52, 15, 50, 23, 17, 11],
       [36, 52, 23,  2, 14, 41],
       [39, 40, 57, 49,  4, 38],
       [34, 10, 26, 13,  9, 51],
       [31, 34, 16, 37,  3, 43],
       [54, 19, 58, 53,  4, 48],
       [34,  9,  7, 17, 21, 13],
       [45, 39, 33, 46,  4, 25]], dtype=int32)

In [106]:
uns + numeros 

array([[36, 10,  4,  8,  5, 23],
       [22, 57, 49, 50, 47, 17],
       [53, 16, 51, 24, 18, 12],
       [37, 53, 24,  3, 15, 42],
       [40, 41, 58, 50,  5, 39],
       [35, 11, 27, 14, 10, 52],
       [32, 35, 17, 38,  4, 44],
       [55, 20, 59, 54,  5, 49],
       [35, 10,  8, 18, 22, 14],
       [46, 40, 34, 47,  5, 26]], dtype=int32)

In [108]:
valores = np.random.randint(1, 3, numeros.shape, dtype=numeros.dtype)
valores

array([[1, 2, 2, 2, 1, 2],
       [1, 2, 1, 2, 2, 2],
       [1, 2, 1, 1, 1, 2],
       [2, 2, 2, 2, 2, 1],
       [2, 2, 1, 1, 1, 2],
       [2, 1, 1, 2, 2, 2],
       [1, 2, 2, 1, 2, 2],
       [2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1],
       [1, 2, 2, 2, 1, 2]], dtype=int32)

In [110]:
numeros * valores

array([[ 35,  18,   6,  14,   4,  44],
       [ 21, 112,  48,  98,  92,  32],
       [ 52,  30,  50,  23,  17,  22],
       [ 72, 104,  46,   4,  28,  41],
       [ 78,  80,  57,  49,   4,  76],
       [ 68,  10,  26,  26,  18, 102],
       [ 31,  68,  32,  37,   6,  86],
       [108,  19, 116,  53,   8,  48],
       [ 68,   9,  14,  17,  42,  13],
       [ 45,  78,  66,  92,   4,  50]], dtype=int32)

In [114]:
(numeros > 50) * uns

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [126]:
numeros

array([[36, 10,  4,  8,  5, 23],
       [22, 57, 49, 50, 47, 17],
       [53, 16, 51, 24, 18, 12],
       [37, 53, 24,  3, 15, 42],
       [40, 41, 58, 50,  5, 39],
       [35, 11, 27, 14, 10, 52],
       [32, 35, 17, 38,  4, 44],
       [55, 20, 59, 54,  5, 49],
       [35, 10,  8, 18, 22, 14],
       [46, 40, 34, 47,  5, 26]], dtype=int32)

In [132]:
numeros = numeros/(180 * 3.14159)

In [136]:
numeros = numeros.astype(np.float16)

In [138]:
numeros

array([[0.06366 , 0.01768 , 0.007072, 0.014145, 0.00884 , 0.04068 ],
       [0.0389  , 0.10077 , 0.0867  , 0.08844 , 0.0831  , 0.03006 ],
       [0.09375 , 0.02829 , 0.0902  , 0.04245 , 0.03183 , 0.02122 ],
       [0.0654  , 0.09375 , 0.04245 , 0.005306, 0.02652 , 0.0743  ],
       [0.07074 , 0.0725  , 0.10254 , 0.08844 , 0.00884 , 0.069   ],
       [0.0619  , 0.01945 , 0.04776 , 0.02477 , 0.01768 , 0.092   ],
       [0.05658 , 0.0619  , 0.03006 , 0.0672  , 0.007072, 0.0778  ],
       [0.0973  , 0.03537 , 0.1043  , 0.0955  , 0.00884 , 0.0867  ],
       [0.0619  , 0.01768 , 0.014145, 0.03183 , 0.0389  , 0.02477 ],
       [0.08136 , 0.07074 , 0.06012 , 0.0831  , 0.00884 , 0.046   ]],
      dtype=float16)

In [150]:
np.sqrt( numeros.astype(np.float32) ) 

array([[0.25230867, 0.13298473, 0.08409785, 0.11893232, 0.0940344 ,
        0.20169267],
       [0.19725595, 0.3174414 , 0.29439756, 0.29738852, 0.28832254,
        0.17337766],
       [0.30618623, 0.16819571, 0.30034974, 0.20603386, 0.17840917,
        0.14568794],
       [0.25579226, 0.30618623, 0.20603386, 0.07284397, 0.16284893,
        0.2725432 ],
       [0.26596946, 0.26927638, 0.32021722, 0.29738852, 0.0940344 ,
        0.26262087],
       [0.2487763 , 0.13948102, 0.21854064, 0.15736903, 0.13298473,
        0.30328202],
       [0.23786464, 0.2487763 , 0.17337766, 0.25922906, 0.08409785,
        0.27896205],
       [0.31191352, 0.18806879, 0.32296917, 0.30906314, 0.0940344 ,
        0.29439756],
       [0.2487763 , 0.13298473, 0.11893232, 0.17840917, 0.19725595,
        0.15736903],
       [0.2852365 , 0.26596946, 0.24519305, 0.28832254, 0.0940344 ,
        0.21445277]], dtype=float32)

In [152]:
np.isnan( numeros )

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [158]:
valores = np.exp( numeros )    # e ** numeros
valores

array([[1.065, 1.018, 1.007, 1.015, 1.009, 1.042],
       [1.04 , 1.106, 1.091, 1.093, 1.087, 1.03 ],
       [1.099, 1.028, 1.095, 1.043, 1.032, 1.021],
       [1.067, 1.099, 1.043, 1.005, 1.027, 1.077],
       [1.073, 1.075, 1.108, 1.093, 1.009, 1.071],
       [1.063, 1.02 , 1.049, 1.025, 1.018, 1.097],
       [1.059, 1.063, 1.03 , 1.069, 1.007, 1.081],
       [1.103, 1.036, 1.11 , 1.101, 1.009, 1.091],
       [1.063, 1.018, 1.015, 1.032, 1.04 , 1.025],
       [1.085, 1.073, 1.062, 1.087, 1.009, 1.047]], dtype=float16)

In [166]:
valores[2, 1:5 ]

array([1.028, 1.095, 1.043, 1.032], dtype=float16)

In [168]:
valores[1:-1, 1:-1]

array([[1.106, 1.091, 1.093, 1.087],
       [1.028, 1.095, 1.043, 1.032],
       [1.099, 1.043, 1.005, 1.027],
       [1.075, 1.108, 1.093, 1.009],
       [1.02 , 1.049, 1.025, 1.018],
       [1.063, 1.03 , 1.069, 1.007],
       [1.036, 1.11 , 1.101, 1.009],
       [1.018, 1.015, 1.032, 1.04 ]], dtype=float16)

In [172]:
valores[ valores > 1.1 ] = 0

In [174]:
valores

array([[1.065, 1.018, 1.007, 1.015, 1.009, 1.042],
       [1.04 , 0.   , 1.091, 1.093, 1.087, 1.03 ],
       [1.099, 1.028, 1.095, 1.043, 1.032, 1.021],
       [1.067, 1.099, 1.043, 1.005, 1.027, 1.077],
       [1.073, 1.075, 0.   , 1.093, 1.009, 1.071],
       [1.063, 1.02 , 1.049, 1.025, 1.018, 1.097],
       [1.059, 1.063, 1.03 , 1.069, 1.007, 1.081],
       [0.   , 1.036, 0.   , 0.   , 1.009, 1.091],
       [1.063, 1.018, 1.015, 1.032, 1.04 , 1.025],
       [1.085, 1.073, 1.062, 1.087, 1.009, 1.047]], dtype=float16)

In [176]:
valores.sum()

np.float16(57.72)

In [184]:
valores.sum(axis=0, keepdims=True)

array([[ 9.62 ,  9.42 ,  8.39 ,  9.46 , 10.24 , 10.586]], dtype=float16)

In [196]:
arr1 = np.array([[1, 2], [3, 4], [5, 19]])
arr2 = np.array([[5, 6], [7, 8], [12, 13]])

In [198]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5, 19]])

In [200]:
arr2

array([[ 5,  6],
       [ 7,  8],
       [12, 13]])

In [210]:
arr3 = arr2.T
print(f"Matrix1 : {arr1.shape}     Matrix2: {arr3.shape}")
arr1 @ arr3

Matrix1 : (3, 2)     Matrix2: (2, 3)


array([[ 17,  23,  38],
       [ 39,  53,  88],
       [139, 187, 307]])

In [208]:
arr1 * arr2

array([[  5,  12],
       [ 21,  32],
       [ 60, 247]])