In [1]:
import numpy as np

In [192]:
import math

In [2]:
tabuleiro = np.zeros( [4, 3] )
tabuleiro

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
tabuleiro = np.ones( [4, 3] )
tabuleiro

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
tabuleiro_com_zeros = np.zeros( [8, 8] )
tabuleiro_com_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
tabuleiro_com_ones = np.ones_like( tabuleiro_com_zeros )
tabuleiro_com_ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
numeros_pares = np.arange( 0, 100, 2 )
numeros_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
numeros_impares = np.arange( 1, 100, 2 )
numeros_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
todos_numeros = np.concatenate( [numeros_pares, numeros_impares] )
todos_numeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98,  1,
        3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [9]:
numeros_aleatorios = np.random.random( (10, 10) )
numeros_aleatorios

array([[0.82948415, 0.76345307, 0.37117183, 0.00273049, 0.39846206,
        0.0151933 , 0.27157336, 0.6366598 , 0.2730597 , 0.95982414],
       [0.60950828, 0.48947091, 0.93039738, 0.97560383, 0.94319218,
        0.31429536, 0.14012738, 0.52186994, 0.43127131, 0.69227002],
       [0.38944798, 0.26213295, 0.46844346, 0.16086485, 0.55485661,
        0.7376203 , 0.54478559, 0.8561284 , 0.59112225, 0.66256796],
       [0.71606218, 0.36327523, 0.26597822, 0.25482409, 0.38828568,
        0.75100495, 0.12424271, 0.85072399, 0.30360143, 0.03756847],
       [0.01518688, 0.38553393, 0.21896232, 0.11668427, 0.60408408,
        0.68047167, 0.75380752, 0.38782775, 0.98129229, 0.69464498],
       [0.58835302, 0.58954263, 0.34982053, 0.65253371, 0.39122571,
        0.81666735, 0.90270629, 0.52853228, 0.62010078, 0.57141729],
       [0.68287809, 0.3779833 , 0.08773772, 0.86669659, 0.31976298,
        0.26749626, 0.73547305, 0.85966884, 0.25122557, 0.80069336],
       [0.16459896, 0.07666888, 0.9728521

In [10]:
numeros_aleatorios_inteiros = np.random.randint( 0, 50, (10, 10) )
numeros_aleatorios_inteiros

array([[14, 34,  9,  5, 48, 40, 26, 14, 13, 35],
       [32, 15, 26, 29, 28, 32, 38,  9, 34, 42],
       [28,  2, 36, 32,  3, 47, 29, 49, 28, 36],
       [25, 16,  1, 49, 38, 22, 12, 45, 38, 47],
       [47, 27, 31,  6, 14, 47, 47,  0, 32, 39],
       [45, 13, 31, 33,  1, 33, 41, 42, 37, 47],
       [14, 35, 10,  6, 36, 25, 42, 34, 29, 39],
       [20, 33, 46, 23, 39, 30, 12, 16, 45, 33],
       [12, 24, 14, 33, 16, 44, 46, 14, 28,  6],
       [13,  1, 30, 19, 22, 43, 31, 33, 38, 31]], dtype=int32)

In [11]:
matriz_identidade_5 = np.eye( 5 ) 
matriz_identidade_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
matriz_identidade_9 = np.eye( 9 ) 
matriz_identidade_9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
matriz_identidade_6 = np.eye( 6 ) 
matriz_identidade_6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
matriz_identidade_6.reshape( (-1, 5 ) )

ValueError: cannot reshape array of size 36 into shape (5)

In [44]:
matriz_identidade_6.flatten()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [46]:
matriz_identidade_6.ravel()

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [54]:
matriz3d = matriz_identidade_6.reshape( (-1, 3, 3  ) )

In [56]:
matriz3d.shape

(4, 3, 3)

In [58]:
matriz3d.ndim

3

In [68]:
matriz_identidade_6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [70]:
matriz_flatten = matriz_identidade_6.flatten()
matriz_ravel = matriz_identidade_6.ravel()

In [72]:
matriz_identidade_6[2, 2] = 3

In [74]:
matriz_identidade_6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [76]:
matriz_flatten

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [78]:
matriz_ravel

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 3., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [86]:
copia  = np.copy(matriz_identidade_6)
view  = matriz_identidade_6

In [88]:
view

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [90]:
matriz_identidade_6[2, 2] = 8

In [92]:
view

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 8., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [94]:
copia

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [104]:
matriz_1x24 = np.arange(1, 25)
matriz_1x24

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [108]:
matriz4x6 = matriz_1x24.reshape( (4, -1) )
matriz4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [110]:
np.transpose(matriz4x6)

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [112]:
matriz4x6.reshape( (6, 4) )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [114]:
matriz4x6.T

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [116]:
np.savez("matriz4x6.npz", matriz=matriz4x6)

In [120]:
dados = np.load("matriz4x6.npz")

In [124]:
dados["matriz"]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [128]:
matriz4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [136]:
matriz4x6_aleatorios = np.random.randint(1, 3, (4, 6))
matriz4x6_aleatorios

array([[1, 1, 1, 1, 2, 1],
       [2, 2, 2, 1, 1, 1],
       [2, 1, 1, 1, 2, 2],
       [2, 1, 1, 2, 1, 1]], dtype=int32)

In [140]:
multiplicacao4x6 = matriz4x6 * matriz4x6_aleatorios
multiplicacao4x6

array([[ 1,  2,  3,  4, 10,  6],
       [14, 16, 18, 10, 11, 12],
       [26, 14, 15, 16, 34, 36],
       [38, 20, 21, 44, 23, 24]])

In [142]:
numeros_maiores_15 = multiplicacao4x6 > 15
numeros_maiores_15

array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [ True, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [144]:
numeros_maiores_15.astype(np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [154]:
matriz4x6

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42, 45, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [152]:
matriz4x6 *= 3

In [158]:
np.sin(matriz4x6)

array([[ 0.14112001, -0.2794155 ,  0.41211849, -0.53657292,  0.65028784,
        -0.75098725],
       [ 0.83665564, -0.90557836,  0.95637593, -0.98803162,  0.99991186,
        -0.99177885],
       [ 0.96379539, -0.91652155,  0.85090352, -0.76825466,  0.67022918,
        -0.55878905],
       [ 0.43616476, -0.30481062,  0.1673557 , -0.02655115, -0.11478481,
         0.25382336]])

In [166]:
np.exp(matriz4x6)

array([[2.00855369e+01, 4.03428793e+02, 8.10308393e+03, 1.62754791e+05,
        3.26901737e+06, 6.56599691e+07],
       [1.31881573e+09, 2.64891221e+10, 5.32048241e+11, 1.06864746e+13,
        2.14643580e+14, 4.31123155e+15],
       [8.65934004e+16, 1.73927494e+18, 3.49342711e+19, 7.01673591e+20,
        1.40934908e+22, 2.83075330e+23],
       [5.68572000e+24, 1.14200739e+26, 2.29378316e+27, 4.60718663e+28,
        9.25378173e+29, 1.85867175e+31]])

In [170]:
resultado_exp = 2.71828 ** matriz4x6
resultado_exp

array([[2.00854964e+01, 4.03427165e+02, 8.10303487e+03, 1.62753478e+05,
        3.26898439e+06, 6.56591741e+07],
       [1.31879711e+09, 2.64886945e+10, 5.32038578e+11, 1.06862589e+13,
        2.14638815e+14, 4.31112715e+15],
       [8.65911288e+16, 1.73922581e+18, 3.49332136e+19, 7.01650936e+20,
        1.40930074e+22, 2.83065048e+23],
       [5.68550201e+24, 1.14196130e+26, 2.29368596e+27, 4.60698210e+28,
        9.25335224e+29, 1.85858173e+31]])

In [172]:
np.sqrt(matriz4x6)

array([[1.73205081, 2.44948974, 3.        , 3.46410162, 3.87298335,
        4.24264069],
       [4.58257569, 4.89897949, 5.19615242, 5.47722558, 5.74456265,
        6.        ],
       [6.244998  , 6.4807407 , 6.70820393, 6.92820323, 7.14142843,
        7.34846923],
       [7.54983444, 7.74596669, 7.93725393, 8.1240384 , 8.30662386,
        8.48528137]])

In [204]:
matriz4x6[2, 2] = 1.0/0.0

ZeroDivisionError: float division by zero

In [210]:
matriz4x6

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42, -1, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [180]:
np.isnan( matriz4x6 )

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [214]:
matriz4x6[::, 2:4 ]

array([[ 9, 12],
       [27, 30],
       [-1, 48],
       [63, 66]])

In [216]:
matriz4x6[1:3, 1:5 ]

array([[24, 27, 30, 33],
       [42, -1, 48, 51]])

In [218]:
matriz4x6[1:-1, 1:-1 ]

array([[24, 27, 30, 33],
       [42, -1, 48, 51]])

In [220]:
matriz4x6

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42, -1, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [222]:
matriz4x6[matriz4x6<0]

array([-1])

In [224]:
matriz4x6[matriz4x6<0] = 0

In [226]:
matriz4x6

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42,  0, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [230]:
np.sum(matriz4x6, axis=0)

array([120, 132,  99, 156, 168, 180])

In [240]:
np.sum(matriz4x6, axis=0, keepdims=True)

array([[120, 132,  99, 156, 168, 180]])

In [242]:
matriz4x6

array([[ 3,  6,  9, 12, 15, 18],
       [21, 24, 27, 30, 33, 36],
       [39, 42,  0, 48, 51, 54],
       [57, 60, 63, 66, 69, 72]])

In [244]:
matriz4x6_aleatorios = np.random.randint(1, 3, (4, 6))
matriz4x6_aleatorios

array([[2, 2, 1, 1, 2, 1],
       [2, 1, 2, 2, 2, 2],
       [2, 2, 1, 1, 2, 2],
       [2, 1, 2, 1, 2, 2]], dtype=int32)

In [250]:
matriz4x6 @ matriz4x6_aleatorios

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [256]:
np.dot(np.array([1, 2, 3]), np.array([4, 5, 6]))

np.int64(32)

In [260]:
matriz6x4_aleatorios = matriz4x6_aleatorios.T


In [262]:
matriz4x6 @ matriz6x4_aleatorios

array([[ 87, 120, 105, 108],
       [249, 318, 285, 288],
       [366, 426, 420, 378],
       [573, 714, 645, 648]])