In [1]:
import numpy as np

In [7]:
tabuleiro = np.zeros( [4, 3] )
tabuleiro

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
tabuleiro = np.ones( [4, 3] )
tabuleiro

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
tabuleiro_com_zeros = np.zeros( [8, 8] )
tabuleiro_com_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
tabuleiro_com_ones = np.ones_like( tabuleiro_com_zeros )
tabuleiro_com_ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
numeros_pares = np.arange( 0, 100, 2 )
numeros_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
numeros_impares = np.arange( 1, 100, 2 )
numeros_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [33]:
todos_numeros = np.concatenate( [numeros_pares, numeros_impares] )
todos_numeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98,  1,
        3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [35]:
numeros_aleatorios = np.random.random( (10, 10) )
numeros_aleatorios

array([[0.44399335, 0.19434154, 0.26718738, 0.43294291, 0.31916575,
        0.70179407, 0.64293682, 0.75978342, 0.96183067, 0.72878012],
       [0.25338988, 0.74330544, 0.00399992, 0.56376454, 0.2057271 ,
        0.20848514, 0.69835157, 0.47410915, 0.00613756, 0.55525398],
       [0.79636049, 0.30198367, 0.42698698, 0.74176443, 0.49007142,
        0.27981605, 0.81895794, 0.96983097, 0.69085757, 0.9820422 ],
       [0.24077686, 0.27410629, 0.14446152, 0.96785247, 0.47533898,
        0.64188741, 0.37293985, 0.32379159, 0.87434953, 0.26289897],
       [0.94882111, 0.94711713, 0.84117757, 0.43331255, 0.34080161,
        0.26836259, 0.96241851, 0.54540982, 0.81323781, 0.81513569],
       [0.04580303, 0.89607481, 0.49494403, 0.0848605 , 0.48053474,
        0.11452433, 0.87621048, 0.2915282 , 0.45692173, 0.09999943],
       [0.13287875, 0.19562481, 0.84889961, 0.46069198, 0.83478454,
        0.20997478, 0.44603534, 0.67753036, 0.464788  , 0.42543726],
       [0.44308566, 0.31811854, 0.2596869

In [37]:
numeros_aleatorios_inteiros = np.random.randint( 0, 50, (10, 10) )
numeros_aleatorios_inteiros

array([[ 2, 32, 34, 35,  0,  8,  7, 43, 20, 32],
       [38, 30, 12, 49, 20, 43,  3, 38,  9,  1],
       [39, 20,  1, 24,  1, 30, 10, 35, 49,  0],
       [ 5, 48, 43, 27, 16, 20,  9, 27, 35, 43],
       [20,  8, 12, 49, 17, 30, 37, 32, 44, 46],
       [24,  3,  5, 47, 34,  9,  1, 16, 14, 49],
       [45,  3, 35, 48,  4, 15, 42, 37, 43, 41],
       [14, 31, 11, 12, 11, 43,  9, 14, 38, 46],
       [12, 40, 42,  5, 11, 34, 45, 49, 49, 29],
       [43, 12, 31, 29, 24,  7, 26, 35, 17, 48]], dtype=int32)